### ISSUE TITLE
KeyBak Mount Front Vertical

### ISSUE THREAD

**Issue by edelapena-dev** [salveoo/genius#1]
Thank you for sharing this MOD, I am making the same change but on a SWX1, the original Keybak front mount does not work because there is no space between the bed and the aluminum frame, in your photos you can see that you modified it to put it Vertical , but it is not in the STL folder, please can you share that piece.

Thanks again.

**Comment by salveoo** [comment]
Hi, I am happy you enjoyed the mod. I am currently on holiday so until
monday I can't access my computer. I am going to send you the step file
when I reach home. If you want to contact me on discord salveo#6988.

Good day

Il mer 28 lug 2021, 17:54 edelapena-dev ***@***.***> ha
scritto:

**Comment by edelapena-dev** [comment]
Thanks ! , enjoy your vacation .
