### ISSUE TITLE
2 copies of Z-Bearing_Block_Left_Keybak_x1.stl needed

### ISSUE THREAD

**Issue by Zeta3D** [salveoo/genius#3]
Great work! I'm preparing the STL to print and I think you need 2 copies of [Z-Bearing_Block_Left_Keybak_x1.stl](https://github.com/salveoo/genius/blob/main/STL/GANTRY/Z-Bearing_Block_Left_Keybak_x1.stl) instead of 1 as the name says.

**Comment by salveoo** [comment]
Thanks! I forgot to add Z-Bearing_Block_Right_x1. Now it's here https://github.com/salveoo/genius/blob/main/STL/GANTRY/Z-Bearing_Block_Right_x1.stl. Enjoy your build :)

**Comment by Zeta3D** [comment]
Thanks!
